# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4106587508387863488a05a02196acbc39523d14e7aad66a0bbc9fd1fa96e0cb2d39efa60ba75f2a76aaf5ffe5c3acf670f4efc2a875a2aebef5f1e40d16daa

test:
  secret_key_base: 5a4b65193eb8ee0181914f825e7127545ffab8c0d016014bfc40ae89b10d06b1ade10fc7443eaa3599788ce3f3b7054a982f139ea9e9828188863a30912bed29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
